{% set version = "6.2.1" %}

package:
  name: ipython
  version: {{ version }}

source:
  fn: ipython-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/i/ipython/ipython-{{ version }}.tar.gz
  sha256: 51c158a6c8b899898d1c91c6b51a34110196815cc905f9be0fa5878e19355608

build:
  number: 0
  script: python -m pip install --no-deps .
  skip: True  # [py2k]
  entry_points:
    - ipython = IPython:start_ipython
    - ipython3 = IPython:start_ipython

requirements:
  build:
    - python
    - pip
  run:
    - python
    - pickleshare
    - simplegeneric >0.8
    - prompt_toolkit >=1.0.3,<2.0.0
    - pygments
    - decorator
    - traitlets
    - pexpect

test:
  commands:
    - ipython -h
    - ipython3 -h
  imports:
    - IPython

about:
  home: http://ipython.org/
  license: BSD 3-clause
  license_file: COPYING.rst
  summary: "IPython: Productive Interactive Computing"
