{% set version = "0.8.1" %}

package:
  name: terminado
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/terminado/terminado-{{ version }}.tar.gz
  sha256: 55abf9ade563b8f9be1f34e4233c7b7bde726059947a593322e8a553cc4c067a

build:
  number: 0
  noarch: python
  script: python setup.py install

requirements:
  build:
    - python
  run:
    - python
    - ptyprocess
    - tornado >=4

test:
  imports:
    - terminado

  requires:
    - nose

  commands:
    - nosetests terminado

about:
  home: http://github.com/mitsuhiko/markupsafe
  license: BSD 3-clause
  summary: Terminals served by tornado websockets
