{% set name = "requests-file" %}
{% set version = "1.4.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8f04aa6201bacda0567e7ac7f677f1499b0fc76b22140c54bc06edf1ba92e2fa

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - requests
    - setuptools
    - six
  run:
    - python
    - requests
    - six

test:
  imports:
    - requests_file

about:
  home: http://github.com/dashea/requests-file
  license: Apache
  license_file: LICENSE
  summary: file transport adapter for Requests
