{% set version = "0.2.4" %}

package:
  name: sqlparse
  version: {{ version }}

source:
  fn: sqlparse-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/s/sqlparse/sqlparse-{{ version }}.tar.gz
  sha256: ce028444cfab83be538752a2ffdb56bc417b7784ff35bb9a3062413717807dec

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - sqlformat = sqlparse.__main__:main

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - sqlparse

about:
  home: https://github.com/andialbrecht/sqlparse
  license: BSD 3-Clause
  license_file: LICENSE
  summary: 'A non-validating SQL parser module for Python.'
  description: |
    sqlparse is a non-validating SQL parser for Python. It provides support
    for parsing, splitting and formatting SQL statements.
  doc_url: https://sqlparse.readthedocs.org
  dev_url: https://github.com/andialbrecht/sqlparse
