{% set version = "1.15.7" %}

package:
  name: setuptools_scm
  version: {{ version }}

source:
  fn: setuptools_scm-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/s/setuptools_scm/setuptools_scm-{{ version }}.tar.gz
  sha256: e163e8a12d2121f77575773cfc2b5988275dc1f1d2541fdf780127c29dbbea9c

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - pip
    - setuptools
  run:
    - python
    - setuptools

test:
  imports:
    - setuptools_scm

about:
  home: https://github.com/pypa/setuptools_scm/
  license: MIT
  summary: 'The blessed package to manage your versions by scm tags.'
