# Full credit goes to https://github.com/conda/conda-recipes for providing this recipe.
# It has been subsequently adapted for automated building with conda-forge.

{% set version = "2.1.2" %}

package:
  name: matplotlib
  version: {{ version }}

source:
  fn: matplotlib-{{ version }}.tar.gz
  url: https://github.com/matplotlib/matplotlib/archive/v{{ version }}.tar.gz
  sha256: 613d79282a0a8ba88cfc52dbcf1b08ab070dae395c3d313d141ccc3f87e3c9fa

build:
    number: 0

requirements:
  build:
    - python
    - setuptools
    - backports.functools_lru_cache
    - numpy 1.11*
    - python-dateutil
    - freetype 2.7.*
    - cycler >=0.10
    - nose
    - pyparsing
    - pytz
    - libpng >=1.6.23,<1.7
    - tk 8.6.*
    - functools32  # [py27]
    - subprocess32 # [py27]
  run:
    - python
    - backports.functools_lru_cache
    - numpy >=1.11
    - cycler >=0.10
    - python-dateutil
    - freetype 2.7.*
    - pytz
    - pyparsing
    - libpng >=1.6.23,<1.7
    - tk 8.6.*
    - functools32  # [py2k]
    - subprocess32 # [py27]
    - setuptools

test:
    imports:
        - matplotlib
        - matplotlib.pyplot
        - mpl_toolkits

about:
  home: http://matplotlib.org/
  license: PSF-based (http://matplotlib.org/users/license.html)
  summary: Publication quality figures in Python
