{% set name = "py" %}
{% set version = "1.5.2" %}
{% set hash_type = "sha256" %}
{% set hash = "ca18943e28235417756316bfada6cd96b23ce60dd532642690dcfdaba988a76d" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/py/py-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash }}

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - py
    - py.code
    - py.io
    - py.log
    - py.path
    - py.process

about:
  home: https://github.com/pytest-dev/py
  license: MIT
  license_file: LICENSE
  summary: "library with cross-python path, ini-parsing, io, code, log facilities"
