{% set name = "msgpack-python" %}
{% set version = "0.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: 0
  noarch: generic

# renamed to msgpack as of version 0.5.0
requirements:
  run:
    - msgpack {{ version }}

test:
  imports:
    - msgpack

about:
  home: http://msgpack.org/
  license: Apache 2.0
  summary: 'MessagePack (de)serializer.'
  license_family: Apache
  dev_url: https://github.com/msgpack/msgpack-python
