{% set name = "html5lib" %}
{% set version = "1.0.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  md5: 942a0688d6bdf20d087c9805c40182ad

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - six >=1.9
    - webencodings

test:
  imports:
    - html5lib

about:
  home: https://github.com/html5lib/html5lib-python
  license: MIT
  license_file: LICENSE
  summary: HTML parser based on the WHATWG HTML specifcation
  description: |
    html5lib is a pure-python library for parsing HTML. It is designed to
    conform to the WHATWG HTML specification, as is implemented by all major
    web browsers.
  doc_url: http://html5lib.readthedocs.org/
  dev_url: https://github.com/html5lib/html5lib-python
