{% set version = "0.8.3" %}

package:
  name: mistune
  version: {{ version }}

source:
  fn: mistune-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/m/mistune/mistune-{{ version }}.tar.gz
  sha256: bc10c33bfdcaa4e749b779f62f60d6e12f8215c46a292d05e486b869ae306619

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - mistune

about:
  home: https://github.com/lepture/mistune
  license:  BSD 3-clause
  summary: The fastest markdown parser in pure Python
