{% set version = "1.0.0" %}

package:
  name: scipy
  version: {{ version }}

source:
  fn: scipy-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/s/scipy/scipy-{{ version }}.tar.gz
  sha256: 87ea1f11a0e9ec08c264dc64551d501fa307289460705f6fccd84cbfc7926d10

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - cython
    - libgfortran
    - openblas 0.2.19
    - numpy 1.11*
  run:
    - python
    - libgfortran
    - openblas 0.2.19
    - numpy >=1.11

test:
  requires:
    - pytest

about:
  home: http://www.scipy.org/
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: Scientific Library for Python
  description: |
    SciPy is a Python-based ecosystem of open-source software for mathematics,
    science, and engineering.
  doc_url: http://www.scipy.org/docs.html
  dev_url: https://github.com/scipy/scipy
