{% set version = "4.3.1" %}
{% set md5 = "b3cddf7db529538d2d079d760a3a7ef2" %}

package:
  name: isort
  version: {{ version }}

source:
  fn: isort-{{version}}.tar.gz
  url: https://pypi.io/packages/source/i/isort/isort-{{ version }}.tar.gz
  md5: {{ md5 }}

build:
    script: python setup.py install --single-version-externally-managed --record=record.txt
    noarch: python
    number: 0

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - isort

about:
  home: https://github.com/timothycrosley/isort
  license: MIT License
  summary: 'A Python utility / library to sort Python imports.'
  description: |
    isort is a Python utility / library to sort imports alphabetically, and
    automatically separated into sections. It provides a command line utility,
    Python library and plugins for various editors to quickly sort all your
    imports. It currently cleanly supports Python 2.6 - 3.5 using pies to
    achieve this without ugly hacks and/or py2to3.
  doc_url: http://isort.readthedocs.io/en/latest/
  dev_url: https://github.com/timothycrosley/isort
