{% set version = "16.0.4" %}
package:
  name: pyzmq
  version: {{ version }}

source:
  fn: pyzmq-{{ version }}.tar.gz
  # We use the pypi URL as it includes the prepared Cython files.
  url: https://pypi.io/packages/source/p/pyzmq/pyzmq-{{ version }}.tar.gz
  sha256: bc23fad15d6da82081e89ea0b254a7b6efe6d1c4c58edb16f28e4b4d880086b2

build:
  number: 0

requirements:
  build:
    - python
    - zeromq 4.1*
    - libsodium
  run:
    - python
    - zeromq 4.1*
    - libsodium

test:
  imports:
    - zmq
    - zmq.backend.cython.socket
    - zmq.backend.cython.utils
    - zmq.devices.monitoredqueue

  requires:
    - pytest

  commands:
    - py.test --pyargs zmq.tests

about:
  home: https://github.com/zeromq/pyzmq
  summary: Python bindings for zeromq
  license: BSD 3-clause
