{%set name = "s3transfer" %}
{%set version = "0.1.12" %}
{%set hash_type = "sha256" %}
{%set hash_val = "10891b246296e0049071d56c32953af05cea614dca425a601e4c0be35990121e" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash_val }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt


requirements:
  build:
    - python
    - setuptools
    - botocore >=1.3.0,<2.0.0
    - futures >=2.2.0,<4.0.0  # [not py3k]

  run:
    - python
    - botocore >=1.3.0,<2.0.0
    - futures >=2.2.0,<4.0.0  # [not py3k]

test:
  imports:
    - s3transfer

about:
  home: https://github.com/boto/s3transfer
  license: Apache 2.0
  summary: 'An Amazon S3 Transfer Manager'
