{% set version = "0.1.3" %}
{% set name = "zict" %}

package:
  name: {{ name }}
  version: "{{ version }}"

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 63377f063086fc92e5c16e4d02162c571f6470b9e796cf3411ef9e815c96b799

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - heapdict

test:
  imports:
    - zict

about:
  home: http://github.com/mrocklin/zict
  license: BSD 3-Clause
  summary: 'Composable Dictionary Classes'
