{% set name = "bleach" %}
{% set version = "2.1.2" %}
{% set sha256 = "38fc8cbebea4e787d8db55d6f324820c7f74362b70db9142c1ac7920452d1a19" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: pip install --no-deps .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - setuptools
    - html5lib >=0.99999999
    - six

test:
  imports:
    - bleach

about:
  home: https://github.com/mozilla/bleach
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Bleach is a whitelist-based HTML sanitizing library that escapes or strips markup and attributes.

  dev_url: https://github.com/mozilla/bleach
  doc_url: https://bleach.readthedocs.io/
