{% set name = "astroid" %}
{% set version = "1.6.1" %}
{% set sha256 = "f0a0e386dbca9f93ea9f3ea6f32b37a24720502b7baa9cb17c3976a680d43a06" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - six
    - lazy-object-proxy
    - wrapt
    - enum34  # [py27]
    - singledispatch  # [py27]
    - backports.functools_lru_cache  # [py27]

  run:
    - python
    - setuptools
    - six
    - lazy-object-proxy
    - wrapt
    - enum34  # [py27]
    - singledispatch  # [py27]
    - backports.functools_lru_cache  # [py27]

test:
  imports:
    - astroid
    - astroid.tests
    # import modutils to expose the setuptools runtime requirement
    - astroid.modutils

about:
  home: https://github.com/PyCQA/astroid
  license: LGPL 2.1
  summary: 'A abstract syntax tree for Python with inference support.'
