{% set version = "3.0" %}

package:
  name: pytest-runner
  version: {{ version }}

source:
  fn: pytest-runner-{{version}}.tar.gz
  url: https://pypi.io/packages/source/p/pytest-runner/pytest-runner-{{version}}.tar.gz
  sha256: 0f7c3a3cf5aead13f54baaa01ceb49e5ae92aba5d3ff1928e81e189c40bc6703

build:
    script: python setup.py install --single-version-externally-managed --record record.txt
    noarch: python
    number: 0

requirements:
  build:
    - python
    - setuptools
    - setuptools_scm >=1.9,!=1.13.1,!=1.14.0

  run:
    - python
    - setuptools
    - pytest

test:
  imports:
    - ptr

about:
  home: https://github.com/pytest-dev/pytest-runner
  license: MIT
  summary: 'Invoke py.test as distutils command with dependency resolution.'
