{% set version = "1.1.0" %}
{% set name = "xlrd" %}
{% set sha256 = "8a21885513e6d915fe33a8ee5fdfa675433b61405ba13e2a69e62ee36828d7e2" %}

package:
  name: {{ name }}
  version: {{ version }}


source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches: # patch required to add the license at the top level
    - patch

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  files:
    - test.xlsx

about:
  home: 'http://www.python-excel.org/'
  license: "BSD 3-Clause and BSD with advertising"
  license_family: BSD
  # copy of github source code in docs/license.rst thanks to the patch
  license_file: LICENSE
  summary: 'Library for developers to extract data from Microsoft Excel (tm) spreadsheet files'
  doc_url: http://xlrd.readthedocs.io/en/latest/
  dev_url: https://github.com/python-excel/xlrd/blob/master/docs/index.rst
