{% set version = "0.6.3" %}

package:
  name: pycosat
  version: {{ version }}

source:
  fn: pycosat-{{ version }}.zip
  url: https://pypi.io/packages/source/p/pycosat/pycosat-{{ version }}.zip
  md5: 51eb7cfe19cf704d4f0c476da61200c0

build:
  number: 0
  script: python setup.py install

requirements:
  build:
    - python

  run:
    - python

test:
  source_files:
    - "*"

  imports:
    - pycosat

about:
  home: https://github.com/ContinuumIO/pycosat
  license: MIT
  summary: Bindings to picosat (a SAT solver)
