{% set version = "5.2.2" %}

package:
  name: jupyter_client
  version: {{ version }}

source:
  fn: jupyter_client-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/j/jupyter_client/jupyter_client-{{ version }}.tar.gz
  sha256: 83d5e23132f0d8f79ccd3939f53fb9fa97f88a896a85114dc48d0e86909b06c4

build:
  number: 0
  script: pip install --no-deps .
  entry_points:
    - jupyter-kernelspec = jupyter_client.kernelspecapp:KernelSpecApp.launch_instance
    - jupyter-run = jupyter_client.runapp:main

requirements:
  build:
    - python
    - pip
  run:
    - python
    - traitlets
    - tornado >=4.1
    - jupyter_core
    - python-dateutil >=2.1
    - pyzmq >=13

test:
  commands:
    - jupyter kernelspec -h
    - jupyter run -h
  imports:
    - jupyter_client

about:
  home: http://jupyter.org
  license: BSD 3-clause
  license_file: COPYING.md
  summary: jupyter_client contains the reference implementation of the Jupyter protocol.
