{% set name = "futures" %}
{% set version = "3.2.0" %}
{% set sha256 = "9ec02aa7d674acb8618afb127e27fde7fc68994c0437ad759fa094a574adb265" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [py>=32]
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - concurrent
    - concurrent.futures

about:
  home: https://github.com/agronholm/pythonfutures
  license: BSD 2-Clause
  license_file: LICENSE
  summary: Backport of the concurrent.futures package from Python 3.2
