{% set name = "ipaddress" %}
{% set version = "1.0.19" %}
{% set sha256 = "200d8686011d470b5e4de207d803445deee427455cd0cb7c982b68cf82524f81" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [py>=33]
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - ipaddress

about:
  home: https://github.com/phihag/ipaddress
  license: PSF 2
  summary: 'IPv4/IPv6 manipulation library'
