{% set version = "0.26" %}

package:
  name: cython
  version: {{ version }}

source:
  fn: Cython-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/C/Cython/Cython-{{ version }}.tar.gz
  sha256: 4c24e2c22ddaed624d35229dc5db25049e9e225c6f64f3364326836cad8f2c66

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - cython = Cython.Compiler.Main:setuptools_main
    - cythonize = Cython.Build.Cythonize:main
    - cygdb = Cython.Debugger.Cygdb:main

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  commands:
    - cython --version
  files:
    - fib.pyx

about:
  home: http://www.cython.org/
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: The Cython compiler for writing C extensions for the Python language
  description: |
    Cython is an optimising static compiler for both the Python programming
    language and the extended Cython programming language. It makes writing C
    extensions for Python as easy as Python itself.
  doc_url: http://cython.org/#documentation
  dev_url: https://github.com/cython/cython
