{% set version = "4.8.0" %}

package:
  name: ipykernel
  version: {{ version }}

source:
  fn: ipykernel-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/i/ipykernel/ipykernel-{{ version }}.tar.gz
  sha256: dedc199df6a38725c732986dfa606c245fb8fe0fe999b33a0c305b73d80c6774

build:
  number: 0
  script:
    - pip install --no-deps .
    - python -m ipykernel install --prefix $PREFIX

requirements:
  build:
    - pip
    - python
    - ipython >=4.0
    - traitlets >=4.1.0
    - jupyter_client
    - tornado >=4.0
  run:
    - python
    - ipython >=4.0
    - traitlets >=4.1.0
    - jupyter_client
    - tornado >=4.0

test:
  imports:
    - ipykernel

about:
  home: http://ipython.org
  license: BSD 3-clause
  license_file: COPYING.md
  summary: IPython Kernel for Jupyter
