{% set name = "bokeh_conda_requirements" %}
{% set version = "0.12.15" %}

package:
  name: {{ name }}
  version: {{ version }}

build:
  number: 0
  noarch: True
  string: py2_0  # [py2k]
  string: py3_0  # [py3k]

requirements:
  run:
    - python 2.*  # [py2k]
    - python 3.*  # [py3k]
    - six >=1.5.2
    - requests >=1.2.3
    - pyyaml >=3.10
    - python-dateutil >=2.1
    - jinja2 >=2.7
    - numpy >=1.7.1
    - packaging >=16.8
    - tornado >=4.3
    - futures >=3.0.3      # [py2k]
    - bkcharts >=0.2

about:
  summary: Requirements meta-package for bokeh
